### ISSUE TITLE
Should python agent use Java 11 instead of 8?

### ISSUE THREAD

**Issue by henrique** [jenkinsci/docker-inbound-agents#32]
### Jenkins and plugins versions report

2.346.1

### What Operating System are you using (both controller, and any agents involved in the problem)?

docker

### Reproduction steps

docker run jenkins/jnlp-agent-python3

### Expected Results

run

### Actual Results

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: hudson/remoting/jnlp/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

### Anything else?

https://github.com/jenkinsci/docker-inbound-agents/blob/master/python/python3/Dockerfile#L5

**Comment by dduportal** [comment]
Hi: we are closing this issue as this repository and associated Docker image are now archived as per #51 .
